### PR TITLE
Update contact.html

### PR DESCRIPTION
**Pull request by Amarish-2309**

### CODE REVIEW

**Comment by utkarshpandey1610** [comment]
looks good but can you please change the paragraphs they some default para can you please look into that

**Comment by utkarshpandey1610** [comment]
and yes ,please  do we have acces to that emai id that you provided in the email section in liine 187 and 188 
 in line 130 and 134 whay there are 2 different phone numbers 
"CHANE ALL PARAGRAPH TAG "
are you sure line 150 is showing correct location on map 
and in line 195 change the number 
please look into this matter

**Comment by utkarshpandey1610** [comment]
Please provide description so that it is easy to look into the changes and review the code efficiently it makes my job easy

**Comment by Amarish-2309** [comment]
Sure i will make changes to the para

**Comment by Amarish-2309** [comment]
Yes we will have the access to the email id that I have provided and the location is correct that i have provided

**Comment by Amarish-2309** [comment]
i will makes all the necessary changes

**Review by utkarshpandey1610 — COMMENTED** [review]
good

**Pull request merged**
